export type TGameData = {
  added: number;
  added_by_status: any[];
  background_image: string;
  clip: any;
  dominant_color: string;
  esrb_rating: any[];
  genres: any[];
  id: number;
  metacritic: number;
  name: string;
  parent_platforms: any[];
  platforms: any[];
  playtime: number;
  rating: number;
  rating_top: number;
  ratings: any[];
  ratings_count: number;
  released: string;
  reviews_count: number;
  reviews_text_count: number;
  saturated_color: string;
  short_screenshots: any[];
  slug: string;
  stores: any[];
  suggestions_count: number;
  tags: any[];
  tba: boolean;
  updated: Date;
  user_game: any;
};

export type TGameResponse = {
  count: number;
  description: string;
  filters: any;
  next: string;
  nofollow: boolean;
  nofollow_collections: string[];
  noindex: boolean;
  previous: null | boolean;
  results: TGameData[];
  seo_description: string;
  seo_h1: string;
  seo_keywords: string;
  seo_title: string;
};
